### ISSUE TITLE
Fix footer position

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter.io#3]
The footer is not fixed at the bottom of the page and short pages look ugly, an example: http://starcounter.io/tutorials/

To fix this the following styles should be added:
```css
html {
    position: relative;
    min-height: 100%;
    padding-bottom: 170px;
}

.fusion-footer {
    position: absolute;
    width: 100%;
    bottom: 0;
}
```

I would do that myself, but I do not have access to the website's source.
